/*
 * Copyright (c) 2026 - Raphael Quintao <raphaelquintao@gmail.com>
 * https://github.com/raphaelquintao/qredshift
 * SPDX-License-Identifier: Apache-2.0
 */

/* Generated by wayland-scanner 1.25.0 */

#include <stdbool.h>
#include <stdlib.h>
#include <stdint.h>
#include "wayland-util.h"

#ifndef __has_attribute
# define __has_attribute(x) 0  /* Compatibility with non-clang compilers. */
#endif

#if (__has_attribute(visibility) || defined(__GNUC__) && __GNUC__ >= 4)
#define WL_PRIVATE __attribute__ ((visibility("hidden")))
#else
#define WL_PRIVATE
#endif

extern const struct wl_interface wl_output_interface;
extern const struct wl_interface zwlr_gamma_control_v1_interface;

static const struct wl_interface *wlr_gamma_control_unstable_v1_types[] = {
	NULL,
	&zwlr_gamma_control_v1_interface,
	&wl_output_interface,
};

static const struct wl_message zwlr_gamma_control_manager_v1_requests[] = {
	{ "get_gamma_control", "no", wlr_gamma_control_unstable_v1_types + 1 },
	{ "destroy", "", wlr_gamma_control_unstable_v1_types + 0 },
};

WL_PRIVATE const struct wl_interface zwlr_gamma_control_manager_v1_interface = {
	"zwlr_gamma_control_manager_v1", 1,
	2, zwlr_gamma_control_manager_v1_requests,
	0, NULL,
};

static const struct wl_message zwlr_gamma_control_v1_requests[] = {
	{ "set_gamma", "h", wlr_gamma_control_unstable_v1_types + 0 },
	{ "destroy", "", wlr_gamma_control_unstable_v1_types + 0 },
};

static const struct wl_message zwlr_gamma_control_v1_events[] = {
	{ "gamma_size", "u", wlr_gamma_control_unstable_v1_types + 0 },
	{ "failed", "", wlr_gamma_control_unstable_v1_types + 0 },
};

WL_PRIVATE const struct wl_interface zwlr_gamma_control_v1_interface = {
	"zwlr_gamma_control_v1", 1,
	2, zwlr_gamma_control_v1_requests,
	2, zwlr_gamma_control_v1_events,
};

