name: release.yml
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      tag_name:
        description: "Existing tag to build and use for the draft release (example: v1.0.0)"
        required: true

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/raphaelquintao/qredshift-cross:debian-13
      volumes:
        - ${{ github.workspace }}:/home/q/qredshift
      env:
        GPG_PRIVATE_KEY: ${{secrets.GPG_PRIVATE_KEY}}

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event_name == 'workflow_dispatch' && format('refs/tags/{0}', inputs.tag_name) || github.ref }}

      - name: Update compiler toolchains
        run: |
          sudo apt-get update
          sudo apt-get upgrade -y --no-install-recommends

      - name: Test
        run: ls -la

#      - name: Build Cross-Compilation Container
#        run: make docker-image
#
#      - name: Cross-Compile Binaries and Linux Packages
#        run: |
#          docker run --rm -v $(pwd):/qredshift  -u "$(id -u):$(id -g)" qredshift-cross:latest make debs
#
#      # Points directly to 'bin/' matching your output files tree structure
#      - name: Create and Upload Draft Release Assets
#        uses: softprops/action-gh-release@v2
#        with:
#          tag_name: ${{ github.event_name == 'workflow_dispatch' && inputs.tag_name || github.ref_name }}
#          generate_release_notes: true
#          draft: true
#          files: |
#            bin/*.deb
#            bin/*.tar.gz
